### PR TITLE
Angular integration

### PR DESCRIPTION
**Pull request by bekicelmir**
## Changes ##

- Implemented Angular SPA under UI folder

Regarding Angular, what's done so far:

- Implemented app routing with separated modules
- Added dashboard, login, register and about pages
- Implemented redux store and added essential services

What needs to be done:
- API integration
- User info modal component
- Migrate current JS to Angular app
- Switch to use Angular Bootstrap components

Could we create separated issues for next steps in order to easily follow integration.
Basic setup should be done with this PR. Let me know if you want something fixed or added first before moving on.

### CODE REVIEW

**Comment by raul1991** [comment]
Started reviewing

**Comment by raul1991** [comment]
I think you are sending a pull request with the same branch which is why I see all the previous commits as well. Can you force push to this branch with only the commits that are relevant for this issue ? That would speed up the process.

**Comment by raul1991** [comment]
Also, let's keep this code in the dev branch and once we have completely migrated it to angular and everything works fine, then we merge it back to the master branch.

**Comment by raul1991** [comment]
Issues detected so far

The css seems to be altered. 
1. the nav bar background color changed
2. favicon not loaded
3. clicking the tabs route to the login page

**Comment by bekicelmir** [comment]
Thanks

I'll make style corrections.

Regarding tabs it needs to be implemented from scratch. Ng Bootstrap Tabs component can be used to get it done.

I'll push updates later.

**Pull request closed without merging**
