### PR TITLE
Added Jinja template inheritance for #12.

### LINKED ISSUE #12: Use templates in flask to extract common parts of the html
To begin with , extract only the script tags and put them inside the template.

### PR DESCRIPTION
**Pull request by seancallaway**
# Description

Many HTML elements were shared across the templates. This pull request adds a `_base.html` template that includes all of the common elements. Additionally, I've adjusted all of the other templates to inherit from and utilize this base template.

This should close #12.

[Use templates in flask to extract common parts of the html](https://github.com/raul1991/monito/issues/12)

## Type of change

Code cleanup. No functionality/features added or changed.

## Where should the reviewer start?

All changes were made in `monito/templates`, so review should be limited to there. While I did my best to ensure that nothing is missing, please check to see that nothing was missed in the roll-up to base.

---

#### Database changes

N/A

#### New ENV variables

N/A

### CODE REVIEW

**Comment by raul1991** [comment]
While I am reviewing this change. I must tell you @seancallaway this is the best pull request description I have ever seen.

**Comment by seancallaway** [comment]
Console looked clear, although I didn't test more than just page loads.

**Comment by raul1991** [comment]
Something went wrong with the fonts and a dialog that used to appear on clicking the + button isn't appearing anymore.

**Comment by seancallaway** [comment]
Let's capture the HTML output before and after the merge.

**Comment by raul1991** [comment]
I removed the commits and it seemed to work after that. Do give it a try at your end.

**Comment by raul1991** [comment]
I can do that as well but I have just captured the screenshots of the problems.

screenshot from 2018-10-17 20-26-41
screenshot from 2018-10-17 20-26-14
screenshot from 2018-10-17 20-24-50
screenshot from 2018-10-17 20-24-42


Notice the faded color of the placeholder on the login form as well as the on the dashboard. The images with normal colors appear when I removed your commits. I find it weird. I think I need to do some digging here. Do help out if you can.

**Pull request merged**
